"use client";

import { motion } from "framer-motion";
import Link from "next/link";

const MainSection = () => {
  const typingAnimation = {
    hidden: { width: 0 },
    visible: {
      width: "auto",
      transition: {
        type: "spring",
        stiffness: 100,
        damping: 10,
        duration: 2,
        delay: 0.3,
      },
    },
  };

  return (
    <section className="relative overflow-hidden min-h-screen grid items-center justify-center p-6 md:p-24 poppins">
      <motion.div
        className="relative flex flex-col md:flex-row items-center justify-between w-full max-w-6xl p-8 bg-white bg-opacity-20 rounded-3xl shadow-lg"
        initial={{ opacity: 0, scale: 0.8 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.6 }}
      >
        <div className="text-center md:text-left md:w-1/2">
          <motion.h1
            className="text-5xl font-extrabold text-white mb-6"
            initial={{ y: -50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            Neural Blogging
          </motion.h1>
          <motion.p
            className="text-xl text-white mb-8"
            initial={{ y: 50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.5 }}
          >
            Create stunning blogs effortlessly with our AI-powered tools. Get
            inspired, write, and publish with ease.
          </motion.p>
          <motion.div
            className="flex justify-center md:justify-start space-x-4"
            initial={{ y: 50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.7 }}
          >
            <Link
              href="/writearticle"
              className="px-6 py-3 bg-purple-700 text-white font-semibold rounded-lg shadow-md hover:bg-purple-800 transition"
            >
              Create AI Blog
            </Link>
          </motion.div>
        </div>
        <div className="md:w-1/2 mt-8 md:mt-0 flex items-center justify-center">
          <motion.div
            className="relative w-full h-64 bg-black bg-opacity-50 rounded-lg p-4"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
          >
            <code className="block text-left text-white font-mono">
              <motion.div
                className="code-line text-green-400"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 0.9 }}
              >
                const blogPost = &quot;AI Generated Blog&quot;;
              </motion.div>
              <motion.div
                className="code-line text-blue-400"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.5, delay: 1.1 }}
              >
                console.log(blogPost);
              </motion.div>
            </code>
            <motion.div
              className=" text-white md:pt-28 pt-12"
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ duration: 0.5, delay: 1.5 }}
            >
              <motion.span
                className="font-bold"
                variants={typingAnimation}
                initial="hidden"
                animate="visible"
              >
                <motion.span
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.05, delay: 0.05 }}
                >
                  I wanna post a blog!
                </motion.span>
              </motion.span>
            </motion.div>
            <motion.div
              className=" text-white bg-purple-700 px-2 py-1 rounded"
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ duration: 0.5, delay: 1.3 }}
            >
              Start your journey with AI blogging!
            </motion.div>
          </motion.div>
        </div>
      </motion.div>
      <motion.div
        className="relative text-white text-center mt-10 px-4 md:px-0"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6, delay: 1.5 }}
      >
        <h2 className="text-3xl font-bold mb-4">
          Look down below to some blogs that are generated by AI
        </h2>
      </motion.div>
    </section>
  );
};

export default MainSection;
